services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      # LOCAL_UID: $(id -u)
    ports:
      - "5432:5432"
    volumes:
    #   - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
      - ./pg_data:/var/lib/postgresql
      - ../data:/data
    # user: '$LOCAL_UID'
    # networks:
    #  - airflow-default
      
   
  pgadmin:
    container_name: pgadmin4_container
    # image: dpage/pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"
    volumes:
      # - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
      - ./pg_admin:/var/lib/pgadmin
    # user: '1000'
    # networks:
    #  - airflow-default

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
 
# volumes:
#   pgdata:
# networks:
#   airflow-default: