version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
    #   - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
      - ./pg_data:/var/lib/postgresql
    user: '1000'
   
  pgadmin:
    container_name: pgadmin4_container
    # image: dpage/pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      # - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
      - ./pg_admin:/var/lib/pgadmin
    user: '1000'

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
 
# volumes:
#   pgdata: